### ISSUE TITLE
some questions from a n00b

### ISSUE THREAD

**Issue by wdfghj** [Hyperclaw79/PokeBall-SelfBot#11]
how do i bulk trade?
btw. is there an "free" autospammer or not?

**Comment by Hyperclaw79** [comment]
Please edit your comments instead of posting a new comment everytime.

Anyways,
>how do i bulk trade?

The latest approach would to add all your pokemon to fav list and use `P^trade @user fav`.
However, if you have pokemon in your fav list which you wanna keep, use `P^id Pokemon_name` to get theirs ids. Then use `P^trade @user id1 id2 id3`.

>btw. is there an "free" autospammer or not?

Nope, autospammer is one of the major feature in the premium version. Consider donating to get this one as it's pretty user friendly and it effective even against built-in spam filters of PokeCord.

>IM Sad :( thé bot Starts up but it wont catch pokemon :(((((

Autocatcher in off by default. You'll need to toggle it one first, using `P^autocatcher on`.

**Comment by wdfghj** [comment]
dixiedrekkerdixiedrekker000000

**Comment by wdfghj** [comment]
dixiedrekkerdixiedrekker000000

**Comment by wdfghj** [comment]
ixiedrekker000000
