### ISSUE TITLE
Query: Info about Auto-duler.

### ISSUE THREAD

**Issue by Fr0sTy7u7** [Hyperclaw79/PokeBall-SelfBot#16]
Will you add more tweaks to it and how does auto-dueller work? owo

**Comment by Hyperclaw79** [comment]
Yes, of course I will make more tweaks. But atm, most of the tweaks are focussed towards the Premium version.

Auto-dueler works in multi-user mode, i.e., you need two selfbots. Both the selfbots can trigger each other and automate the commands sequentially based on the bot's reference. 
You can use this to farm as much credits as you want and all it takes is a bit of manual monitoring (since Pokecord's lag can keep the selfbot waiting at times). Although, I am actively modifying this to automatically send pings and trigger pokecord. 

Is that anything you'd like to know in detail?

**Comment by Fr0sTy7u7** [comment]
Btw if I have 100 pokemons set in my priority list will it catch all of those 100 pokemons if theyve spawned in?

**Comment by Hyperclaw79** [comment]
of course

**Comment by Fr0sTy7u7** [comment]
Ooo, gonna set all the legendaries in my priority list and turn on a spambot xD

**Comment by Hyperclaw79** [comment]
hmmm, not needed. Legendaries are all already treated as priority by
default.

As for a spambot, I highly recommend not using an external spambot as you
might get flagged and it might also affect the efficiency of the selfbot.
Like, imagine a Mewtwo spawned and before your selfbot could catch it. the
spambots spams and you catch a Ratatta instead. XD

The built in spammer in the premium version is battle-tested against spam
detectors. It also has a logical switch to let the pokemon be caught before
the next spam while maintaining a perfect time interval, so as, not to slow
things down too much.

**Comment by Fr0sTy7u7** [comment]
owo

**Comment by Fr0sTy7u7** [comment]
How do ya'll even code these bots? It was hard for me to get it adjusted 😞

**Comment by Hyperclaw79** [comment]
With practice lol.
