### ISSUE TITLE
bulk trade

### ISSUE THREAD

**Issue by bueluke** [Hyperclaw79/PokeBall-SelfBot#18]
i setup the bulk trade it starts going finishes after 10 min, message pops up in cmd saying traded away all pokemon i go to discord -pokemon and it says i still have 356 pokemon.. so its not sending all the pokemon away to my main. then it keeps spamming -n in the discord...

**Comment by Hyperclaw79** [comment]
It doesn't trade any pokemon that are in your priority list. You need to use ids or trade by fav method to trade those forcefully.

>then it keeps spamming -n

That is the auto-pokelog upon trade. `-n` is to go to next page. Looks like Pokecord is lagging terribly atm. That's why the bot is getting stuck. I am facing latency issues on my end as well.
Let's wait for Miles to fix the lag issue on PokeCord itself.

**Comment by Hyperclaw79** [comment]
Closing this as this doesn't really seem to be an issue with the bot itself.
