### ISSUE TITLE
"invalid syntax" or  "No module named 'discord'"

### ISSUE THREAD

**Issue by xElfenlied** [Hyperclaw79/PokeBall-SelfBot#64]
As instructed I at first went into the catcher folder (cd xxx/xxx/SelfBot-master). Than i used the command 
`pip install -r requirements.txt`
![2018-05-31 15_02_50-selfbot-master](https://user-images.githubusercontent.com/39309657/40783874-1db78590-64e4-11e8-9000-ab72172f4b99.png)
because i got the error message `Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-d_K6GN/aiohttp/`

i tryed to download aiohttp with `sudo pip install aiohttp`
![2018-05-31 15_08_32-pi raspberrypi_ _bots_selfbot-master](https://user-images.githubusercontent.com/39309657/40784033-a1161dde-64e4-11e8-9b53-964c90e16e89.png)
new error message new try to fix it myself 😓 ... python version to old? no way 🤔 
typed in `python` than 2x tap 
![2018-05-31 15_11_25-pi raspberrypi_ _bots_selfbot-master](https://user-images.githubusercontent.com/39309657/40784133-03a413ca-64e5-11e8-90d3-ccc2197d31ff.png)
i knew i got another newer version of python :P 
than i changed the `pip` to `pip3` (`sudo pip3 install aiohttp`)
and it seemed to succssesfully install everything...

now that i have aiohttp back to the `pip install -r requirements.txt` which still gives to same error as above.. so change it to `pip3 install -r requirements.txt`
which seems to have been succssesfull again.. 

now that the requirements r installed i should be finnaly able to launch the bot

but as i guess the normal `python launcher.py` didn't work and gave this error `SyntaxError: invalid syntax`
![2018-05-31 15_21_07-pi raspberrypi_ _bots_selfbot-master](https://user-images.githubusercontent.com/39309657/40784582-54edcb76-64e6-11e8-9148-eec2b09e9a42.png)

so i tryed `python3 launcher.py` but than i got the error ` No module named 'discord'`
![2018-05-31 15_23_02-pi raspberrypi_ _bots_selfbot-master](https://user-images.githubusercontent.com/39309657/40784797-edbeacf8-64e6-11e8-8854-6bab10db6ea8.png)

and now i am out of ideats how to fix it 😓 🤔

**Comment by Hyperclaw79** [comment]
Lol you have every version except the one where it actually works.... `Py3.6.4`.
That `ModuleNotFoundError` is because your pip install failed at `aiohttp` and `discord.py` is after that.
I suggest you either get rid of all the other versions and freshly install 3.6.4 or install it in a virtual environment. Google `venv` for the instructions as that is beyond the scope of support for the bot.

I will be closing this for now as it is not an issue with the bot itself, but feel free to reopen it if you're still not able to fix it after installing 3.6.4.
