### ISSUE TITLE
Incorrect Disclaimer

### ISSUE THREAD

**Issue by MilesPokecord** [Hyperclaw79/PokeBall-SelfBot#96]
The disclaimer seems to be wrong, it says:
"Selfbots violate discord & PokeCord TOS and you can get banned. Be careful about how you use the bot."
When really it should say:
"Selfbots violate discord & PokeCord TOS and you WILL get banned. Be careful about how you use the bot."

I hope you fix this soon :)

**Comment by Hyperclaw79** [comment]
Lol Miles himself opened an Issue? GG.

---

Fixed in https://github.com/Hyperclaw79/PokeBall-SelfBot/commit/df76fe57cebce14feb1e2987c8e366a6b1c7604c.

---

I assume that you not removing the "Be careful..." part implies that some of the features are within the scope of PokeCord ToS. Correct me if I am wrong.
