### ISSUE TITLE
Autocatcher Broken

### ISSUE THREAD

**Issue by MilesPokecord** [Hyperclaw79/PokeBall-SelfBot#98]
The premium autocatcher doesn't work, don't bother fixing.

**Comment by MateeTheGod** [comment]
lol what a fuckin savage

**Comment by Hyperclaw79** [comment]
Well, thanks to you @MilesPokecord setting up a mole in my existing donors, it got patched. 
But well, I was expecting this. So I'll be hitting the code again.

**Comment by MilesPokecord** [comment]
Have fun!

**Comment by MilesPokecord** [comment]
Might wanna update the README so people don't pay for nothing ;)

**Comment by MateeTheGod** [comment]
miles is such a troll man

**Comment by Hyperclaw79** [comment]
Dw, I don't sell my code till it is working at the time of purchase XD
Gg trying to use this issue to threaten the buyers haha
Just like the way you told one of my donors that I ratted to you about him
😂

**Comment by Hyperclaw79** [comment]
Nope it doesn't but don't worry man, I won't send you the source code to let
you fix it so easily again. XD  





On Fri, Jun 22, 2018 9:57 PM, Miles notifications@github.com  wrote:
Does that come with a money back guarantee if I fix it within a few hours?
Because otherwise people will be losing out man.

**Comment by MilesPokecord** [comment]
But how do you know which one I am 🤔

**Comment by Hyperclaw79** [comment]
Well I am already succeeding if you are wasting your time in here and buying
code from me again instead of making updates on Pokecord  

As for the donors, I am being vigilant from now onwards.  





On Fri, Jun 22, 2018 11:05 PM, Miles notifications@github.com  wrote:
But how do you know which one I am 🤔

**Comment by Hyperclaw79** [comment]
Anyways, this isn't supposed to be a Issue to be discussed on GitHub.
As it is a bug in the Premium Version, refrain from getting the matters here.

If the autocatcher doesn't work in the Premium Version, I will let my donors know about it before they buy. 

Since it is technically irrelevant here, I am closing this issue.
